---
abstract: 'Suite of modules to interact with Docker'
author:
  - 'Javier Gomez <alambike@gmail.com>'
  - 'Francisco Maseda <frmadem@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.42
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.120351'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Eixo-Docker
provides:
  Eixo::Docker:
    file: lib/Eixo/Docker.pm
    version: 1.062
  Eixo::Docker::Api:
    file: lib/Eixo/Docker/Api.pm
    version: 0
  Eixo::Docker::Config:
    file: lib/Eixo/Docker/Config.pm
    version: 0
  Eixo::Docker::Container:
    file: lib/Eixo/Docker/Container.pm
    version: 0
  Eixo::Docker::ContainerException:
    file: lib/Eixo/Docker/ContainerException.pm
    version: 0
  Eixo::Docker::ContainerResume:
    file: lib/Eixo/Docker/ContainerResume.pm
    version: 0
  Eixo::Docker::HostConfig:
    file: lib/Eixo/Docker/HostConfig.pm
    version: 0
  Eixo::Docker::Image:
    file: lib/Eixo/Docker/Image.pm
    version: 0
  Eixo::Docker::ImageCommit:
    file: lib/Eixo/Docker/ImageCommit.pm
    version: 0
  Eixo::Docker::ImageResume:
    file: lib/Eixo/Docker/ImageResume.pm
    version: 0
  Eixo::Docker::Job:
    file: lib/Eixo/Docker/Job.pm
    version: 0
  Eixo::Docker::RequestRawStream:
    file: lib/Eixo/Docker/RequestRawStream.pm
    version: 0
  Eixo::Docker::Terminal:
    file: lib/Eixo/Docker/Terminal.pm
    version: 0
recommends:
  HTTP::Server::Simple::CGI: 0
requires:
  Eixo::Base: 1
  Eixo::Rest: 1
  JSON: 2.5
  Net::HTTP: 6.06
  perl: 5.008001
resources:
  license: http://apache.org/licenses/LICENSE-2.0
version: 1.062
